[project]
name = "sudononomicon"
version = "0.3.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4",
    "fastapi",
    "flask",
    "mccole",
    "pandas",
    "psutil",
    "requests",
    "requests_toolbelt",
    "uvicorn[standard]"
]

[tool.mccole]
skips = ["CONTRIBUTING.md", "old", "templates"]

[tool.mccole.renames]
"README.md" = ""
"CODE_OF_CONDUCT.md" = "conduct"
"LICENSE.md" = "license"
"bibliography.md" = "bibliography"
"glossary.md" = "glossary"
